---
- hosts: php
#  sudo: yes

  tasks:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - mcrypt
      - nginx
      - php7.0-cli
      - php7.0-curl
      - php7.0-fpm
      - php7.0-intl
      - php7.0-json
      - php7.0-mcrypt
      - php7.0-sqlite3
      - sqlite3

  - name: ensure php7.0-fpm cgi.fix_pathinfo=0
    lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
    notify:
      - restart php7.0-fpm
      - restart nginx

  - name: enable php7.0 mcrypt module
    shell: phpenmod mcrypt
    args:
      creates: /etc/php7.0/cli/conf.d/20-mcrypt.ini

  handlers:
    - name: restart php7.0-fpm
      service: name=php7.0-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

